//! # LLM Auto Optimizer - gRPC API
//!
//! Production-ready gRPC API implementation with enterprise-grade quality.
//!
//! ## Features
//!
//! - **Protocol Buffers 3**: Type-safe message definitions
//! - **All RPC Types**: Unary, server streaming, client streaming, bidirectional
//! - **HTTP/2 with TLS 1.3**: Secure communication
//! - **Interceptors**: Authentication, logging, rate limiting, error handling
//! - **Streaming**: Real-time metrics, events, and interactive sessions
//! - **Health Checks**: gRPC standard health checking protocol
//! - **Reflection**: Dynamic client discovery
//!
//! ## Services
//!
//! - **OptimizationService**: Optimization operations with all RPC patterns
//! - **ConfigService**: Configuration management
//! - **MetricsService**: Real-time metrics streaming
//! - **IntegrationService**: External integration management
//! - **HealthService**: Health checks and readiness probes
//! - **AdminService**: Administrative operations
//!
//! ## Example
//!
//! ```no_run
//! use llm_optimizer_api_grpc::{GrpcServer, GrpcServerConfig};
//!
//! # async fn example() -> anyhow::Result<()> {
//! let config = GrpcServerConfig::default();
//! let server = GrpcServer::new(config).await?;
//! server.serve().await?;
//! # Ok(())
//! # }
//! ```

#![warn(missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
#![allow(
    clippy::module_name_repetitions,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc
)]

pub mod auth;
pub mod error;
pub mod interceptors;
pub mod server;
pub mod services;
pub mod streaming;

// Re-export commonly used types
pub use auth::{Claims, Permission, TokenManager};
pub use error::{ApiError, Result};
pub use server::{GrpcServer, GrpcServerConfig, TlsConfig};

/// Generated protobuf code
/// This module will be populated by build.rs
pub mod proto {
    // Include generated files
    #![allow(missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]

    // Common types - this will be generated by tonic-build
    pub mod common {
        tonic::include_proto!("llm.optimizer.common");
    }

    // Optimization service
    pub mod optimization {
        tonic::include_proto!("llm.optimizer.optimization");
    }

    // Config service
    pub mod config {
        tonic::include_proto!("llm.optimizer.config");
    }

    // Metrics service
    pub mod metrics {
        tonic::include_proto!("llm.optimizer.metrics");
    }

    // Integrations service
    pub mod integrations {
        tonic::include_proto!("llm.optimizer.integrations");
    }

    // Health service
    pub mod health {
        tonic::include_proto!("llm.optimizer.health");
    }

    // Admin service
    pub mod admin {
        tonic::include_proto!("llm.optimizer.admin");
    }
}

/// Library version
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Get the library version
pub fn version() -> &'static str {
    VERSION
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        let version = version();
        assert!(!version.is_empty());
    }
}
